<?php
/**
 * @file
 * Code for the Commerce Marketplace Products feature.
 */

include_once 'commerce_ogmk_products.features.inc';

/**
 * Hooks.
 */

/**
 * Implements hook_menu().
 */
function commerce_ogmk_products_menu() {
  $items['user/%user/orders'] = array(
    'title'            => 'My Orders',
    'access callback'  => '_commerce_ogmk_products_user_orders_access',
    'access arguments' => array(1),
    'page callback'    => '_commerce_ogmk_products_user_orders_page',
    'page arguments'   => array(1),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => -10,
    'file'             => 'commerce_ogmk_products.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function commerce_ogmk_products_theme($existing, $type, $theme, $path) {
  return array(
    'user_orders_page' => array(
      'variables' => array('variables' => NULL),
      'template'  => 'templates/pages/user-orders',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function commerce_ogmk_products_entity_info_alter(&$entity_info) {
  /**
   * @Issue(
   *   "Maybe this should be moved to a base ogmk module"
   *   type="task"
   *   priority="low"
   *   labels="modularity"
   * )
   */
  $entity_info['node']['view modes']['ogmk_bootstrap_media'] = array(
    'label' => t('OGMK Bootstrap Media'),
    'custom settings' => FALSE,
  );
}

/**
 * Functions for internal use.
 */

/**
 * Access callback for the My Orders page.
 *
 * @param object $requestedUser
 *   The user for whom to display the orders.
 */
function _commerce_ogmk_products_user_orders_access($requestedUser) {
  global $user;
  if ($user->uid === 1 || $user->uid == $requestedUser->uid) {
    return TRUE;
  }

  return FALSE;
}
