<?php
/**
 * @file
 * Code for the Commerce Marketplace Products feature.
 */

include_once 'commerce_ogmk_products.features.inc';

/**
 * Hooks.
 */

/**
 * Implements hook_menu().
 */
function commerce_ogmk_products_menu() {
  $items['user/%user/orders'] = array(
    'title'            => 'My Orders',
    'access callback'  => '_commerce_ogmk_products_user_orders_access',
    'access arguments' => array(1),
    'page callback'    => '_commerce_ogmk_products_user_orders_page',
    'page arguments'   => array(1),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => -10,
    'file'             => 'commerce_ogmk_products.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function commerce_ogmk_products_theme($existing, $type, $theme, $path) {
  return array(
    'user_orders_page' => array(
      'variables' => array('variables' => NULL),
      'template'  => 'templates/pages/user-orders',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function commerce_ogmk_products_entity_info_alter(&$entity_info) {
  /**
   * @Issue(
   *   "Maybe this should be moved to a base ogmk module"
   *   type="task"
   *   priority="low"
   *   labels="modularity"
   * )
   */
  $entity_info['node']['view modes']['ogmk_bootstrap_media'] = array(
    'label' => t('OGMK Bootstrap Media'),
    'custom settings' => FALSE,
  );
}

/**
 * Public API.
 */

/**
 * @param int|object $product
 *   The product id or object for whom to check if there is a referencing node.
 * @param string $node_type
 *   The node type to look for.
 *
 * @return int
 *   Zero (0) if there is no node referencing the product.
 *   The node's id otherwise.
 */
function commerce_ogmk_products_product_has_node($product, $node_type = 'product') {
  $productId = NULL;
  if (is_int($product)) {
    $productId = $product;
  } else {
    $productId = $product->product_id;
  }

  // Get the Shop owned by the user.
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node', '=')
    ->propertyCondition('type', $node_type)
    ->fieldCondition('field_products_ref', 'product_id', $productId, '=');
  $result = $query->execute();

  if (empty($result['node'])) {
    return 0;
  }

  // Get the first key of the result array because there should be only one
  // result.
  return key($result['node']);
}

/**
 * @param int|object $product
 *   The product id or object for whom to check if there is a referencing node.
 * @param string $node_type
 *   The node type to look for.
 *
 * @return null|object
 *   NULL if there is no node referencing the product.
 *   The node's object otherwise.
 */
function commerce_ogmk_products_product_get_node($product, $node_type = 'product') {
  $nodeId = commerce_ogmk_products_product_has_node($product, $node_type);

  if ($nodeId) {
    return node_load($nodeId);
  }

  return NULL;
}

/**
 * Functions for internal use.
 */

/**
 * Access callback for the My Orders page.
 *
 * @param object $requestedUser
 *   The user for whom to display the orders.
 */
function _commerce_ogmk_products_user_orders_access($requestedUser) {
  global $user;
  if ($user->uid === 1 || $user->uid == $requestedUser->uid) {
    return TRUE;
  }

  return FALSE;
}
