<?php
/**
 * @file
 * Code for the Commerce Marketplace Products feature.
 */

include_once 'ogmk_products.features.inc';

/**
 * Hooks.
 */

/**
 * Implements hook_theme().
 */
function ogmk_products_theme($existing, $type, $theme, $path) {
  return array(
    'user_orders_page' => array(
      'variables' => array('variables' => NULL),
      'template'  => 'templates/pages/user-orders',
    ),
  );
}

/**
 * Implements hook_commerce_line_item_type_info().
 *
 * Provides a custom line item type for 'ogmk_product' products.
 */
function ogmk_products_commerce_line_item_type_info() {
  $line_item_types = array();

  $line_item_types['ogmk_product'] = array(
    'name' => t('Product'),
    'description' => t('Line item for OGMK products'),
    'product' => TRUE,
    'add_form_submit_value' => t('Add product'),
    'base' => 'commerce_product_line_item',
    'callbacks' => array(
      'title' => '_ogmk_products_line_item_title__ogmk_product',
    ),
  );

  return $line_item_types;
}

/**
 * Implements hook_commerce_cart_product_add().
 */
function ogmk_products_commerce_cart_product_add($order, $product, $quantity, $line_item) {
  // Set a status message that the product was successfully added to the cart.
  $title = commerce_line_item_title($line_item);
  drupal_set_message(
    t(
      'The "%title" product has been added to <a href="!cart-url">your cart</a>.',
      array(
        '%title'    => $title,
        '!cart-url' => url('cart')
      )
    )
  );
}

/**
 * Implements hook_commerce_cart_product_remove().
 */
function ogmk_products_commerce_cart_product_remove($order, $product, $quantity, $line_item) {
  // Set a status message that the product was successfully removed from the
  // cart.
  $title = commerce_line_item_title($line_item);
  drupal_set_message(
    t(
      'The "%title" product has been removed from <a href="!cart-url">your cart</a>.',
      array(
        '%title'    => $title,
        '!cart-url' => url('cart')
      )
    )
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ogmk_products_form_views_form_commerce_cart_form_default_alter(&$form, &$form_state, $form_id) {
  // Alter the form submit callbacks so that we override the message displayed
  // when a product is removed from the cart.
  if (!empty($form['edit_delete'])) {
    foreach(element_children($form['edit_delete']) as $key) {
      $form['edit_delete'][$key]['#submit'] = array(
        'views_form_views_form_submit',
        '_ogmk_products_line_item_delete_form_submit',
      );
    }
  }
}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 */
function ogmk_products_inline_entity_form_table_fields_alter(&$fields, $context) {
  if (
    $context['parent_entity_type'] !== 'node' ||
    $context['parent_bundle'] !== 'ogmk_product' ||
    $context['field_name'] !== 'ogmk_products_ref'
  ) {
    return;
  }

  // Add the 'ogmk_weight' field on the table.
  $fields['commerce_price']['weight'] = 3;
  $fields['ogmk_weight'] = array(
    'type' => 'field',
    'label' => t('Weight'),
    'weight' => 4,
  );
}

/**
 * Implements hook_node_insert().
 */
function ogmk_products_node_insert($node) {
  _ogmk_products_generate_skus($node);
}

/**
 * Implements hook_node_update().
 */
function ogmk_products_node_update($node) {
  _ogmk_products_generate_skus($node);
}

/**
 * Callbacks.
 */

/**
 * Line item title callback.
 *
 * @Issue(
 *   "Take into account internationalisation as well"
 *   type="bug"
 *   priority="low"
 *   labels="internationalisation"
 * )
 */
function _ogmk_products_line_item_title__ogmk_product($line_item) {
  $product_id = (int) $line_item->commerce_product[LANGUAGE_NONE][0]['product_id'];
  $node = ogmk_products_product_get_node($product_id);

  $title = check_plain($node->title);

  if (count($node->ogmk_products_ref[LANGUAGE_NONE]) > 1) {
    $product = commerce_product_load($product_id);
    $title .= ', ' . check_plain($product->title);
  }

  return $title;
}

/**
 * Form submit callback to show the line item delete message.
 */
function _ogmk_products_line_item_delete_form_submit($form, &$form_state) {
  $line_item_id = $form_state['triggering_element']['#line_item_id'];

  // Get the corresponding wrapper to show the correct title.
  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $form_state['line_items'][$line_item_id]);

  // If the deleted line item is a product we do not display a message. We will
  // be displaying it via hook_commerce_cart_product_remove() because the line
  // item here seems to have already been deleted and we cannot get the proper
  // line item title.
  if (in_array($line_item_wrapper->getBundle(), commerce_product_line_item_types())) {
    return;
  }

  $title = $line_item_wrapper->line_item_label->value();
  drupal_set_message(t('%title removed from your cart.', array('%title' => $title)));
}

/**
 * Public API.
 */

/**
 * @param int|object $product
 *   The product id or object for whom to check if there is a referencing node.
 * @param string $node_type
 *   The node type to look for.
 *
 * @return int
 *   Zero (0) if there is no node referencing the product.
 *   The node's id otherwise.
 */
function ogmk_products_product_has_node($product, $node_type = 'ogmk_product', $access_bypass = FALSE) {
  $productId = NULL;
  if (is_int($product)) {
    $productId = $product;
  } else {
    $productId = $product->product_id;
  }

  // Get the "product" node that corresponds to the given "commerce_product"
  // entity.
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node', '=')
    ->propertyCondition('type', $node_type)
    ->fieldCondition('ogmk_products_ref', 'product_id', $productId, '=');

  if ($access_bypass) {
    $query->addTag('DANGEROUS_ACCESS_CHECK_OPT_OUT');
  }

  $result = $query->execute();

  if (empty($result['node'])) {
    return 0;
  }

  // Get the first key of the result array because there should be only one
  // result.
  return key($result['node']);
}

/**
 * @param int|object $product
 *   The product id or object for whom to check if there is a referencing node.
 * @param string $node_type
 *   The node type to look for.
 *
 * @return null|object
 *   NULL if there is no node referencing the product.
 *   The node's object otherwise.
 */
function ogmk_products_product_get_node($product, $node_type = 'ogmk_product', $access_bypass = FALSE) {
  $nodeId = ogmk_products_product_has_node($product, $node_type, $access_bypass);

  if ($nodeId) {
    return node_load($nodeId);
  }

  return NULL;
}

/**
 * Functions for internal use.
 */

/**
 * Set the SKU for a created or updated product variant.
 *
 * Generate and save the SKU for commerce_product entities, so that they follow
 * the pattern 'S%shop_id%P%product_id%V%variant_id%', where 'product_id' is the
 * corresponding node id and 'variant_id' is the commerce product's id.
 *
 * This function is expecting the product node as an argument and is being
 * called by hook_node_insert/update() hooks. We do so, instead of using
 * hook_entity_insert/update() hooks for the inserted/updated commerce_product
 * entities, because the variants are created using inline entity forms and they
 * may orphaned variants (without a shop or product node association) until the
 * product node is actually saved.
 *
 * @param object $node The product node that holds the variants for which SKUs
 *                     will be generated.
 *
 * @Issue(
 *   "Support customisation of the SKU pattern through an api hook and/or a
 *   system variable"
 *   type="improvement"
 *   priority="low"
 *   labels="modularity"
 * )
 */
function _ogmk_products_generate_skus($node) {
  if ($node->type !== 'ogmk_product') {
    return;
  }

  $node_wrapper = entity_metadata_wrapper('node', $node);
  $variants = $node_wrapper->ogmk_products_ref->value();

  // Nothing to do if the product has no variants yet.
  if (empty($variants)) {
    return;
  }

  // We will need the shop id.
  /**
   * @Issue(
   *   "Get the shop identifier only instead of loading the full node"
   *   type="improvement"
   *   priority="low"
   *   labels="performance"
   * )
   */
  $shop = $node_wrapper->ogmk_shop_ref->value();

  // Generate and save the SKU for each variant.
  foreach ($variants as $variant) {
    // When the variant is first created, it contains a timestamp-based number
    // as the SKU. If the SKU starts with 'S', we have already generated the SKU
    // for the variant - we don't need to do it again.
    if (strpos($variant->sku, 'S') === 0) {
      continue;
    }

    // Generate the SKU and save the variant.
    $variant->sku = 'S' . $shop->nid . 'P' . $node->nid . 'V' . $variant->product_id;
    entity_save('commerce_product', $variant);
  }
}
